130 clicking on an asset and/or getting back to list/card view view causes a crash (#131)
* Fix connector prop changing on every page change using memo()

Error: The connectors prop passed to Web3ReactProvider must be referentially static. If connectors is changing, try providing a key prop to Web3ReactProvider that changes every time connectors changes.

* use contracts addresses as IDs

* prettier